version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-minor", "version-update:semver-major" ]
    groups:
      spring:
        patterns:
          - "org.springframework.boot:*"
          - "org.springframework:*"
        update-types:
          - "patch"
