version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-minor", "version-update:semver-major" ]
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - "patch"
